FROM alpine as build
ENV SPEEDTESTVERSION="0.10.0.20-1.173ad8d"
ENV SPEEDTESTARCH="x86_64"
ENV SPEEDTESTPLATFORM="linux"
ENV SCRATCH="/scratch"
ENV TINI_VERSION="v0.18.0"
RUN mkdir ${SCRATCH}
ADD https://ookla.bintray.com/download/ookla-speedtest-${SPEEDTESTVERSION}-${SPEEDTESTARCH}-${SPEEDTESTPLATFORM}.tgz /tmp/speedtest.tgz
RUN tar -xvf /tmp/speedtest.tgz -C ${SCRATCH} && \
    chmod +x ${SCRATCH}/speedtest
ADD https://curl.haxx.se/ca/cacert.pem ${SCRATCH}/etc/ssl/cert.pem
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static ${SCRATCH}/tini
RUN chmod +x ${SCRATCH}/tini
# RUN apk add upx && upx --brute ${SCRATCH}/speedtest ${SCRATCH}/tini

FROM scratch
COPY --from=build /scratch/ /
ENTRYPOINT ["/tini", "-s", "/speedtest", "--"]